dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-05/run.sh |
  bash
notifications:
  slack:
    secure: qaAlE7CYrdaRmY6l/apZqc+WXETQOjI8bBeFX64S9QBBdTzckHdGm33XPloQ6fhNmmXdj3UQg4diGdQPtVtaFwSm/8+C+Mj8oPxyTz8iXzs3UQMtxtHssnHx58SnJnnDGpLrO32Ds2w3LEyG9gbxDL/+jRNDPkSTwxY6Fxw1sIQ6MPXN9CUk2+Gj8wLHXw0GKGkH/p1phtNkqr74W7HmNhBQEMqm6C74jKYwGXQnKciT3AHr6u9n0oO+itSYKJ1HT/2qPz1zTgyhL9m4BT852ZGnhDxZ1PKuG45DFZ6fMv2zimYHKYnIcdv6vaMiu7Ic/cnrNM4URJGH0PAtnYj4Tm8+VjsEMd710cbcqWGokVqeKlQgF9JmUaMhLtf3l1UIi1klQsR1vYVm0B3xOFTC+or+3uEoPxft00KFlJapmzyUJAl/bayj3ac887IWVhQPhCk0vDtcSU2diKddp5dO7gHMx9vEm//XPBuHbbjE5qjbjrPD1LDbCkttAmazwma9N0b7APb1y+MNi4ZXJd9oyuQKsNuGeTDtNC6kE8xIXmgDZwzOJb8AoH7DaazX/y/Y2+SehxTACcyFRHpDhQ8fEc1+qzWwAD5lcefv4nFdF8JQPxUJe/oFWblt7cC6tP9rVfK7IP/JkbMNKbT2NnkP6om05ESwRhje5iiT59ukNco=
